### PR TITLE
updated Rotation gesture to include locations and centre

### PR DESCRIPTION
**Pull request by Ollstar**
Updated rotation gesture to work like the other gestures. Includes a locations array and center point.

### CODE REVIEW

**Comment by aleph7** [comment]
We definitely need the center point, but do we really need the array of locations?

**Comment by C4Framework** [comment]
Yes. the other gestures have the `locations` variable, better to be consistent. And, yes, we've already used the locations to track multiple touch points.

**Comment by aleph7** [comment]
Ok, will merge into a 1.2.x branch since this is a braking change

**Comment by C4Framework** [comment]
Dandy

**Pull request closed without merging**
