### PR TITLE
Add Image

### PR DESCRIPTION
**Pull request by C4Framework**
All basic functionality for C4Image is in place including:
* loading images from urls
* loading images from bundle
* individual filters
* multiple filters
* animating image contents

Example:
```
let url = NSURL(string:"http://www.c4ios.com/img/logo.png")
``` 

```
let url = NSURL(string:"localFilename")
```

### CODE REVIEW

**Comment by aleph7** [comment]
That's a lot of commits with a lot of noise, squash them into a singe commit: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by C4Framework** [comment]
I ran git rebase on Add-Image and got the following result:

```
SlantBookPro:c4ios travis$ git rebase -i Add-Image~6
[detached HEAD e5fbbca] Add Initialization Methods
 6 files changed, 353 insertions(+), 112 deletions(-)
 create mode 100644 C4UI/C4Image+Filter.swift
 create mode 100644 C4UI/C4Image+GaussianBlur.swift
 create mode 100644 C4UI/C4Image+Sepia.swift
 delete mode 100644 C4UI/C4ImageProtocol.swift
Successfully rebased and updated refs/heads/Add-Image.
SlantBookPro:c4ios travis$ 
```

I then pushed all the changes as a single commit, but it doesn't appear that anything's changed here...

I also tried reverting the commits, but got lost in that.

From now on I can squash my commits. I thought that multiple commits would be clearer, small chunks of code to review with better commit messages.

**Comment by aleph7** [comment]
C4Image looks good but filters look a bit messy, do you want to have another stab at it based on my comments?

**Comment by C4Framework** [comment]
Most recent push: https://github.com/C4Framework/C4iOS/commit/51f21b9977d240a899964fbb444ef19f4d95a815

Works like this:
```
let url = NSURL(string:"http://www.c4ios.com/img/logo.png")

var gaussImage = C4Image(url: url!)
view.add(gaussImage)

var sepiaImage = C4Image(url: url!)
sepiaImage.origin = C4Point(100,0)
view.add(sepiaImage)

var gaussSepiaImage = C4Image(url: url!)
gaussSepiaImage.origin = C4Point(200,0)
view.add(gaussSepiaImage)

let gauss = C4Image.gaussianBlur(2.0)
let sep = C4Image.sepia(5.0)

let a = C4ViewAnimation(duration: 10.0) {
    gaussImage.apply(gauss)
}

let b = C4ViewAnimation(duration: 10.0) {
    sepiaImage.apply(sep)
}

let c = C4ViewAnimation(duration: 10.0) {
    gaussSepiaImage.apply(filters:[gauss,sep])
}

delay(1.0) {
    a.animate()
    b.animate()
    c.animate()
}
```

Only question I have is: do we need to subclass CIFilter, to create a C4Filter object? It would essentially be a straight wrapper like C4Object or C4Font as per: https://github.com/C4Framework/C4iOS/commit/1035d1a6d4dbf799ae66a7049b0a9943d90f1610

**Pull request closed without merging**
